# new yaml format for python logging config
# see https://docs.python.org/3/library/logging.config.html for description of dictConfig
version: 1
formatters:
  base:
    format: "%(asctime)-18s @%(name)-23s [%(levelname)-8s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: base
    stream: ext://sys.stderr
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: base
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: base
    filename: logging/dereferencer-debug.log
    mode: "a" # in stead of 'w'
loggers:
  __main__:
    level: DEBUG
    propagate: yes
  tests:
    level: DEBUG
    propagate: yes
  dereferencer:
    level: DEBUG
    propagate: yes
  apscheduler:
    level: WARN
    propagate: yes
  pytravharv:
    level: DEBUG
    propagate: yes
root:
  level: DEBUG
  handlers: [stdout, file]
