{#- Jinja Template for Sparql Query
 | Lists instances of certain type with their (optional) schema:name, skos:prefLabel, dc:title or rdf:??
 | variables in template:
 |    - (optional) N: number of results you want (defaults to no limits --> full listing)
 |    - (optional) O: offset to apply when paging
 -#}
PREFIX schema: <https://schema.org/>

SELECT 
  (?s as ?person) 
  ?name 
WHERE { 
	?s a schema:Person .
    OPTIONAL {
        ?s schema:name ?name
    }
}
{{ "OFFSET " ~ O  if O else "" }} {#- add offset statement if provided #}
{{ "LIMIT " ~ N   if N else "" }} {#- add limit  statement if provided #}